SHIFT_ROW_SEPARATOR = "::"
DEFAULT_LOCATION_ID = "loc-default"
DEFAULT_LOCATION_NAME = "Default"
DEFAULT_SUB_SHIFT_MINUTES = 8 * 60
DEFAULT_SUB_SHIFT_START_MINUTES = 8 * 60
DEFAULT_SUB_SHIFT_START = "08:00"
